Update setup.py
This is done due to getting an error when installing the library like this `pip3 install git+https://github.com/ProdPerfect/monday.git`
without requests being installed. It happens because you first import from monday package which requires requests to be installed so you get an error: 
ModuleNotFoundError: No module named 'requests'. 
So I moved __version__, __author__ and __email__ 
to the setup.py file directly without having to import moday.